### ISSUE TITLE
List doesn't update if the items themself change, maintaining the same length

### ISSUE THREAD

**Issue by reneweteling** [orgsync/react-list#83] opened 2016-01-27 08:27 UTC
I have a view with some tabs, if you change a tab you'll get a different user. Only when the amount of items are the same, the view doesnt get updated. 

````cjsx
<div className="table-responsive" style={{ maxHeight: @state.height, overflow: 'auto' }}>
        <ReactList
          itemsRenderer={@itemsRenderer}
          itemRenderer={@itemRenderer}
          length={@state.items.length} 
          type='simple'
          translate3d={true}
        />
</div>
````

A quick console.log in the itemRenderer proves that the row's are not updated / rendered. My solution now is to add a ref to the reactlist and forceupdate it

````cjsx
@refs.list.forceUpdate()
....
 <ReactList ref="list"
````

All suggestions are more than welcome, thanks!

![image](https://cloud.githubusercontent.com/assets/3830933/12607764/af658280-c4d7-11e5-98fb-bb85ac6f830f.png)
![image](https://cloud.githubusercontent.com/assets/3830933/12607766/b4a2093a-c4d7-11e5-8e31-ffe5e30efa90.png)

**Comment by caseywebdev** [comment] 2016-01-27 13:16
This is a duplicate of #36.

Also, I see you're using a `translated3d` prop when you probably meant `useTranslate3d`.

**Closed by caseywebdev** 2016-01-27 13:16 UTC

**Comment by reneweteling** [comment] 2016-01-27 14:57
Ah! Thanks!
