### ISSUE TITLE
Error: Cannot resolve module 'react-dom' 

### ISSUE THREAD

**Issue by ripple0328** [orgsync/react-list#52] opened 2015-09-25 08:31 UTC
ERROR in ./~/react-list/react-list.js
	Module not found: Error: Cannot resolve module 'react-dom' in /node_modules/react-list
 @ ./~/react-list/react-list.js 38:170-190

in local it won't run into the condition to require this package,
but in CI it did, and it not a dependency in react-list

**Comment by caseywebdev** [comment] 2015-09-25 12:01
I don't understand, this seems like an issue with your CI then? If you're using React 0.14.x, you should also have ReactDOM, but if you're using React 0.13.x, you don't need ReactDOM. I don't think there's a way to specify this condition in the dependencies.

**Comment by oliviertassinari** [comment] 2015-09-25 16:58
I have the same issue. I'm using react v0.13.3 and webpack.

**Comment by caseywebdev** [comment] 2015-09-25 17:01
Presumable webpack is trying to be clever and sniff all the `require` statements? Any ideas on a workaround for this?

**Comment by caseywebdev** [comment] 2015-09-25 17:15
I guess we could trick webpack with something like

```js
typeof require === 'function' ? eval('require')('react-dom') :
```

It aint pretty but it might work. @oliviertassinari could you make that change locally and see if webpack stops complaining?

**Comment by oliviertassinari** [comment] 2015-09-25 17:16
Sure, let me try.

**Comment by oliviertassinari** [comment] 2015-09-25 17:23
Yeap, it's working for me.

**Comment by caseywebdev** [comment] 2015-09-25 18:33
Fixed in `0.6.7`

**Closed** 2015-09-25 18:33 UTC

**Comment by oliviertassinari** [comment] 2015-09-25 19:28
@caseywebdev Thanks

**Comment by taion** [comment] 2015-09-29 00:24
@caseywebdev 

This actually breaks Webpack when using React 0.14, though - Webpack can't deal with the `eval('require')`, so it doesn't handle the dependency at all.

Would it be possible to switch this to just use `React.findDOMNode` for now? I think now that it might be impossible to support both React 0.13 and React 0.14 with the same code.

**Comment by caseywebdev** [comment] 2015-09-29 00:26
I don't use webpack, but surely you can manually include `react-dom` in your build, right?

**Comment by taion** [comment] 2015-09-29 00:43
The problem is that the `eval('require')` statement makes it all the way to the browser, and immediately causes an exception.

**Comment by caseywebdev** [comment] 2015-09-29 00:46
But shouldn't you have a module named `react-dom`? If that's the case `require('react-dom')` should work just fine.

**Comment by taion** [comment] 2015-09-29 01:10
I do. The problem (same one as the other webpack users above actually) is that webpack resolves imports statically when possible, and `require` is not actually defined in the browser.

I think it might be possible to force dynamic resolution by doing something like `require('react-dom' + '')`. Let me give this a try when I get near a computer and get back to you.
