### ISSUE TITLE
Question: Rerender already loaded items

### ISSUE THREAD

**Issue by martin-svk** [orgsync/react-list#89] opened 2016-02-15 14:07 UTC
Hello, 

I am wondering if and how can I do this:

1. I need to highlight currently active (last clicked) list item. 
2. I also have checkbox in every list item and I need to show `checked` chechboxes for the items which were selected.

I am using `type="simple"` with custom `itemsRenderer` and `itemRenderer`. Snippets:

```javascript
<table className={tableClassess}>
    <thead>
    ...
    </thead>
    <ReactList itemsRenderer={this._renderItems}
        itemRenderer={this._renderItem}
        length={this.props.data.size}
        pageSize={20}
        type="simple" />
</table>
``` 

```javascript
_renderItems(items, ref) {
    return (
        <tbody ref={ref}>
            { items }
        </tbody>
    );
}
```

```javascript
_renderItem(index, key) {
    const item = this.props.data.get(index);
    return (
        <ResultListItem key={key}
            id={item.id}
            selectHandler={this._handleSelected}
            clickHandler={this._handleClicked}
            isActive={this.state.activeKeyword == item.keyword}
            isSelected={this.props.selectedKeywords.indexOf(item.keyword) > -1}
            keyword={item.keyword}
    );
}
```

But it looks like the items already present in list are never rerendered again. So the `isActive` and `isSelected` props are never changed. Is this true, or I am doing something wrong? If it is true, is there a way to force them to rerender? Or is there another solution for my problem?

Thank You all.

**Comment by caseywebdev** [comment] 2016-02-15 16:05
This is a duplicate of #36 and #83. Check #36 for the solution.

**Closed by caseywebdev** 2016-02-15 16:05 UTC
Labels: duplicate

**Comment by martin-svk** [comment] 2016-02-15 20:34
Ok, Thanks. Sorry for duplicate. Will try that out!
