### ISSUE TITLE
Items not being update when item props change

### ISSUE THREAD

**Issue by nye** [orgsync/react-list#93] opened 2016-02-29 21:08 UTC
Hi!

I'm not sure if I'm doing something wrong but I'm having problems whith list items no being updated when props change.

I have a list with items in ReactList

```
<ReactList
    itemRenderer={this.renderItem}
    length={items.length}
    type="simple"
    pageSize={PAGE_SIZE}
    view={preferences.listView}
/>
```

Every item has a button to mark it as Favourite. This button triggers an Action and then it should receive new props and show a Fav icon. This works fine if use `items.map(function(listItem){...})` but when using ReactList, items are not updated. When clicking this fav button nothing change but when I reload the page, the state has been changed.

Seems like `itemRenderer` should trigger when an item is updated. Am i wrong?

Thank you!

**Comment by caseywebdev** [comment] 2016-02-29 23:20
Duplicate of #36.

ReactList has no notion of your `items` object, so it can't know to update when you modify it.

**Closed by caseywebdev** 2016-02-29 23:20 UTC
