### ISSUE TITLE
Example of how to use scrollTo and other methods

### ISSUE THREAD

**Issue by wldcordeiro** [orgsync/react-list#90] opened 2016-02-18 22:21 UTC
It'd be nice to see examples of how to utilize these.

**Comment by caseywebdev** [comment] 2016-02-19 03:39
Gonna close this as a dupe of #35

**Closed by caseywebdev** 2016-02-19 03:39 UTC
Labels: duplicate

**Comment by caseywebdev** [comment] 2016-02-19 03:42
The gist is you create a ref and call the methods on that ref.

```js
class MyComponent extends Component {
  scrollSomewhere() {
    this.list.scrollTo(Math.floor(Math.random() * 100));
  }

  render() {
    return (
      <div>
        Here is my list:
        <ReactList length={100} itemRenderer={...} ref={c => this.list = c} />
        <button onClick={::this.scrollSomewhere}>Scroll Somewhere</button>
      </div>
    );
  }
}
```
