### ISSUE TITLE
ReactList component does not update after item order change

### ISSUE THREAD

**Issue by webyak** [orgsync/react-list#64] opened 2015-11-02 18:21 UTC
Because the `length` props wont increase/decrease after an item order change within the given array, the component won't update (see `shouldComponentUpdate`).

What do you think about passing down the whole array of items as props, instead of just the `length`?

P.S. Love the component so far, it's one of the smartest infinity scrollers!

**Comment by caseywebdev** [comment] 2015-11-02 20:42
This is a duplicate of https://github.com/orgsync/react-list/issues/36. You have a couple simple options to make this work, both outlined in that issue.

**Closed by caseywebdev** 2015-11-02 20:42 UTC
