### ISSUE TITLE
Zero height issues when type is variable

### ISSUE THREAD

**Issue by rmdort** [orgsync/react-list#81] opened 2016-01-09 12:04 UTC
You can replicate the issue here

http://jsbin.com/mulamuketi/edit?html,js,output

The list is not visible because the component height is zero

![image](https://cloud.githubusercontent.com/assets/118231/12215932/3b473822-b70c-11e5-9beb-485624f3cf5b.png)

**Comment by caseywebdev** [comment] 2016-01-09 13:56
Looks like the container has to have `max-height: xxx` and `overflow: auto` to reproduce. It is also only reproducible for a small `length`. The list shows up fine at `length` >= 6 in your example. I'll take a look.

**Comment by caseywebdev** [comment] 2016-01-09 14:22
Fixed in `0.7.11`

**Closed** 2016-01-09 14:22 UTC
Labels: bug
